image: docker

services:
  - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  environment: production
  script:
    - chmod u+x init-app.sh 
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose up
  only:
    - main

