image: docker

services:
  - docker:dind

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose up -d
  only:
    - main

