version: '3.8'
services:
  production_app:
    build: .
    container_name: nodejs-omni
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${PORT}:${PORT}'
    command: >
      bash -c "./init-app.sh"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
