version: '3.8'
services:
  api:
    image: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  default:
    external: true
    name: backend-network
