version: '3.8'
services:
  app:
    image: registry.gitlab.com/mlgroup/omni-leaf-backend/webhook
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: postgres-omni

networks:
  default:
    external: true
    name: backend-network
