version: '3.8'
services:
  development_app:
    build: .
    container_name: nodejs-omni-dev
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: postgres-omni
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${PORT}:${PORT}'
    command: >
      bash -c "./init-app.sh"
networks:
  default:
    external: true
    name: backend-network
